# Site settings
author: David Braslow
title: Learning Data Science
header-img: img/home-bg.png
email: david.braslow@gmail.com
copyright_name: David Braslow
description: > # this means to ignore newlines until "baseurl:"
  Exploring the intersection between data science and education
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: DavidBraslow
github_username:  DavidBraslow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
